name = "rcart-pixel"
uid = "4c30be39-4ac7-0db5-e766-1f300a0e21e0f6045e8f"
type = "web_pixel"
runtime_context = "strict"

[settings]
  type = "object"

  [settings.fields.pixelId]
    type = "single_line_text_field"
    name = "Meta Pixel ID"
    description = "Your Meta (Facebook) Pixel ID — found in Meta Events Manager."
